Feat/answers on form
algolia/algoliasearch-zendesk pull request #139
Opened 2021-06-10 14:47 UTC by alphonseb

This PR adds an Algolia Answer search when typing the subject of the request on a zendesk contact page, and displays the best answer (if it exists).

Note: with the way this is done, the user would be required to insert in zendesk one code block on the homepage template (for the autocomplete), and one code block on the new request template. To make the integration easier, we could possibly refactor so that only one code block has to be inserted (in the document head template for instance, with of course the downside that it would be loaded on every zendesk page). Happy to discuss it!

2021-06-11 12:00 UTC, redox commented
> Note: with the way this is done, the user would be required to insert in zendesk one code block on the homepage template (for the autocomplete), and one code block on the new request template.

I think this is acceptable :)

2021-06-11 12:07 UTC, redox requested changes
Some minor feedback, but this is promising!

2021-06-11 12:07 UTC, redox commented on app/src/ticketForm.js
> +
Same, let's ensure we add some nice error handling is `suggestionsListSelector` is not found.

2021-06-11 12:07 UTC, redox commented on app/src/ticketForm.js
> +    const buildUrl = (hit) => `${baseUrl}${locale}/articles/${hit.id}`;
Let's probably move `buildUrl` to a helper/util file, as it's used in 2 files now.

2021-06-11 12:07 UTC, redox commented on app/src/ticketForm.js
> +        window.location = e.target.href;
I think you can just do 

```js
const onClick = (e, item) => { self.trackClick(item, item.__position, item.__queryID); }
```

and not prevent the default behavior which you seem to anyway reimplement with `
window.location = e.target.href;` isn't it?

2021-06-11 12:07 UTC, redox commented on app/src/ticketForm.js
> +                              highlightedTagName: 'strong',
Use `mark` instead of `strong` for highlighing, better semantically.

2021-06-11 12:07 UTC, redox commented on app/src/ticketForm.js
> +      document.querySelector(inputSelector).parentNode,
validate if `inputSelector` is found?

2021-06-11 12:07 UTC, redox commented on app/src/translations.js
> +  },
Nice :) I've used GSheet's `GOOGLETRANSLATE` function for this in the past :)

2021-06-11 13:19 UTC, alphonseb commented
This version is published on npm and can be previewed [here](https://algolia-test.zendesk.com/hc/en-gb/requests/new).

2021-06-14 09:24 UTC, redox approved these changes
LGTM

2021-06-14 12:40 UTC, merged